#!/bin/sh

PIP3_DISABLE_VERSION_CHECK_ARG=--disable-pip-version-check
(pip3 --help | grep -- ${PIP3_DISABLE_VERSION_CHECK_ARG}) || PIP3_DISABLE_VERSION_CHECK_ARG=
python3 -m pip install ${PIP3_DISABLE_VERSION_CHECK_ARG} -e .[test]
py.test-3
